//! The simulator and TraceLab must derive the *same* plan from the same file.
//!
//! Matching column names prove nothing: the two systems parse independently, in
//! different languages, and could agree on the header while disagreeing on which
//! round follows which, or on which tokens are cache-eligible. This test pins the
//! only claim that matters — given one canonical trace, both produce byte-equal
//! normalized plans.
//!
//! The fixture is real: it is generated by TraceLab's `tracegen` from the public
//! syfi coding-agent dataset, and shipped alongside the plan TraceLab exported
//! for it. Comparing against TraceLab's own output, rather than a hand-written
//! expectation, is the point.

use std::path::PathBuf;

use serde::Deserialize;
use simulator::sim::frontend::{
    ArrivalMode, CapacityLimit, SessionDependency, TraceDeclaration, TraceFrontend,
};

/// TraceLab's exported plan row. Deserialized rather than compared as raw JSON so
/// a field reordering in either exporter does not read as a disagreement.
#[derive(Debug, Clone, PartialEq, Deserialize)]
struct ExpectedPlanRow {
    request_id: String,
    session_id: String,
    round_idx: usize,
    session_arrival_time_ms: String,
    predecessor_request_id: Option<String>,
    prefix_len: u32,
    input_len: u32,
    output_len: u32,
    tool_wait_after_ms: String,
}

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("trace")
        .join(name)
}

#[test]
fn simulator_plan_matches_tracelab_plan_for_the_same_canonical_trace() {
    let trace_path = fixture("session_execution_v2_example.csv");
    let plan_path = fixture("session_execution_v2_example.plan.json");
    if !trace_path.exists() || !plan_path.exists() {
        eprintln!(
            "skipping: canonical fixture not present at {}",
            trace_path.display()
        );
        return;
    }

    let declaration =
        TraceDeclaration::parse_with_schema("text_generation", &[], "session-execution-v2")
            .expect("canonical declaration");
    let frontend = TraceFrontend::load(
        &[trace_path],
        &declaration,
        ArrivalMode::TraceTimed { request_rate: 1.0 },
        CapacityLimit::unlimited(),
        SessionDependency::Chained,
    )
    .expect("canonical trace loads");

    let expected: Vec<ExpectedPlanRow> =
        serde_json::from_str(&std::fs::read_to_string(&plan_path).expect("read plan"))
            .expect("parse TraceLab plan");

    let actual: Vec<ExpectedPlanRow> = frontend
        .plan_rows()
        .into_iter()
        .map(|row| ExpectedPlanRow {
            request_id: row.request_id,
            session_id: row.session_id,
            round_idx: row.round_idx,
            session_arrival_time_ms: row.session_arrival_time_ms,
            predecessor_request_id: row.predecessor_request_id,
            prefix_len: row.prefix_len,
            input_len: row.input_len,
            output_len: row.output_len,
            tool_wait_after_ms: row.tool_wait_after_ms,
        })
        .collect();

    assert_eq!(
        actual.len(),
        expected.len(),
        "row count differs; row order is part of the plan and is not normalized away"
    );
    for (index, (actual_row, expected_row)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_eq!(
            actual_row, expected_row,
            "plan row {index} differs between the simulator and TraceLab"
        );
    }
}
