"""Resolve `hf://` artifact references in an expanded config to local files.

A token corpus is hundreds of megabytes and is not source: it is a recording,
it is regenerated by re-running a capture, and its identity is the FNV-1a
checksum inside its own manifest -- which the simulator verifies on every load.
So a preset names it by repository and revision, and this module fetches it.
What lives in git is the reference, not the bytes.

A reference is `hf://<repo>@<revision>/<path>`. The revision is required and
must be a commit sha: a branch or tag can move, and a corpus that moved under
a built config would silently reprice every profiled shape rather than fail.

Resolution runs during expansion, including under `--dry-run`. A dry-run's job
is to prove the run is valid, and a corpus that cannot be fetched is exactly
the kind of invalidity worth catching before a GPU is allocated.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

HF_SCHEME = "hf://"

_REFERENCE = re.compile(r"^hf://(?P<repo>[^@/]+/[^@/]+)@(?P<revision>[0-9a-f]{7,40})/(?P<path>.+)$")


class CorpusError(RuntimeError):
    """A reference that cannot be parsed or fetched."""


def _download(repo: str, revision: str, path: str) -> Path:
    from huggingface_hub import hf_hub_download

    return Path(hf_hub_download(repo_id=repo, filename=path, revision=revision))


def resolve_reference(reference: str) -> str:
    """Fetch one `hf://` reference and return the local path it resolved to.

    A token corpus manifest names its payload in `data_file`, relative to
    itself, so that file is fetched too -- the hub's snapshot layout mirrors the
    repository, which puts the two back in one directory.
    """
    match = _REFERENCE.match(reference)
    if not match:
        raise CorpusError(
            f"{reference!r} is not hf://<owner>/<repo>@<commit-sha>/<path>; "
            "a revision is required and must be a commit sha, not a branch or tag"
        )
    repo, revision, path = match["repo"], match["revision"], match["path"]
    try:
        local = _download(repo, revision, path)
    except Exception as exc:  # noqa: BLE001 — the hub raises a wide family
        raise CorpusError(f"fetching {reference}: {exc}") from exc

    if local.name.endswith(".json"):
        try:
            data_file = json.loads(local.read_text()).get("data_file")
        except json.JSONDecodeError as exc:
            raise CorpusError(f"{reference} is not readable JSON: {exc}") from exc
        if isinstance(data_file, str) and data_file:
            payload = _download(repo, revision, str(Path(path).parent / data_file))
            if payload.parent != local.parent:
                raise CorpusError(
                    f"{reference}: the hub placed {data_file} in {payload.parent}, "
                    f"not beside its manifest in {local.parent}"
                )
    return str(local)


def resolve_hf_references(config):
    """Replace every `hf://` string leaf in an expanded config with its file.

    Applied to the whole tree rather than to named keys: the scheme is
    unambiguous, and an artifact field that gains hub hosting later should not
    need this module edited to work.
    """
    if isinstance(config, dict):
        return {key: resolve_hf_references(value) for key, value in config.items()}
    if isinstance(config, list):
        return [resolve_hf_references(value) for value in config]
    if isinstance(config, str) and config.startswith(HF_SCHEME):
        return resolve_reference(config)
    return config
