"""Resolve `hf://` capture references in an expanded config to local files.

A capture (a token corpus, an expert popularity profile) is a recording, not
source: it is regenerated by re-running a capture, and a token corpus is
hundreds of megabytes. So a preset names it by repository and revision, and
this module fetches it. What lives in git is the reference, not the bytes.

Captures live in a Hugging Face dataset repo, so a reference is
`hf://datasets/<owner>/<repo>@<revision>/<path>`, the form `huggingface_hub`
writes. The revision is required and must be a commit sha: a branch or tag can
move, and a capture that moved under a built config would silently reprice
every profiled shape rather than fail.

Resolution runs during expansion, including under `--dry-run`. A dry-run's job
is to prove the run is valid, and a corpus that cannot be fetched is exactly
the kind of invalidity worth catching before a GPU is allocated.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

HF_SCHEME = "hf://"

#: Each measured routing kind and the arch field naming its capture. A row of
#: another routing (`uniform`, `random`) is synthetic and names none.
ROUTING_FILES = {"popularity": "expert_popularity_file", "corpus": "token_corpus_file"}

_REFERENCE = re.compile(
    r"^hf://datasets/(?P<repo>[^@/]+/[^@/]+)@(?P<revision>[0-9a-f]{7,40})/(?P<path>.+)$"
)


class CorpusError(RuntimeError):
    """A reference that cannot be parsed or fetched."""


def _download(repo: str, revision: str, path: str) -> Path:
    from huggingface_hub import hf_hub_download

    return Path(
        hf_hub_download(repo_id=repo, repo_type="dataset", filename=path, revision=revision)
    )


def _fetch(repo: str, revision: str, path: str) -> Path:
    """Download one file of a reference; a failure is a `CorpusError`, which is
    all a caller catches."""
    try:
        return _download(repo, revision, path)
    except Exception as exc:  # noqa: BLE001 — the hub raises a wide family
        raise CorpusError(f"fetching hf://datasets/{repo}@{revision}/{path}: {exc}") from exc


def resolve_reference(reference: str) -> str:
    """Fetch one `hf://` reference and return the local path it resolved to.

    A token corpus manifest names its payload in `data_file`, relative to
    itself, so that file is fetched too -- the hub's snapshot layout mirrors the
    repository, which puts the two back in one directory.
    """
    match = _REFERENCE.match(reference)
    if not match:
        raise CorpusError(
            f"{reference!r} is not hf://datasets/<owner>/<repo>@<commit-sha>/<path>; "
            "captures live in a dataset repo, and the revision must be a commit sha, "
            "not a branch or tag"
        )
    repo, revision, path = match["repo"], match["revision"], match["path"]
    local = _fetch(repo, revision, path)

    if local.name.endswith(".json"):
        try:
            data_file = json.loads(local.read_text()).get("data_file")
        except json.JSONDecodeError as exc:
            raise CorpusError(f"{reference} is not readable JSON: {exc}") from exc
        if isinstance(data_file, str) and data_file:
            payload = _fetch(repo, revision, str(Path(path).parent / data_file))
            # The loader resolves `data_file` against the manifest's directory,
            # so that is where the hub must have put it -- a subdirectory too.
            if payload != local.parent / data_file:
                raise CorpusError(
                    f"{reference}: the hub placed {data_file} at {payload}, "
                    f"not where its manifest in {local.parent} names it"
                )
    return str(local)


def resolve_hf_references(config):
    """Replace every `hf://` string leaf in an expanded config with its file.

    Applied to the whole tree rather than to named keys: the scheme is
    unambiguous, and an artifact field that gains hub hosting later should not
    need this module edited to work.
    """
    if isinstance(config, dict):
        return {key: resolve_hf_references(value) for key, value in config.items()}
    if isinstance(config, list):
        return [resolve_hf_references(value) for value in config]
    if isinstance(config, str) and config.startswith(HF_SCHEME):
        return resolve_reference(config)
    return config
