"""Resolve `hf://` artifact references in an expanded config to local files.

A token corpus is hundreds of megabytes and is not source: it is a recording,
it is regenerated by re-running a capture, and its identity is the FNV-1a
checksum inside its own manifest -- which the simulator verifies on every load.
So a preset names it by repository and revision, and this module fetches it.
What lives in git is the reference, not the bytes.

A reference is `hf://<repo>@<revision>/<path>`. The revision is required and
must be a commit sha: a branch or tag can move, and a corpus that moved under
a built config would silently reprice every profiled shape rather than fail.

Resolution runs during expansion, including under `--dry-run`. A dry-run's job
is to prove the run is valid, and a corpus that cannot be fetched is exactly
the kind of invalidity worth catching before a GPU is allocated.

The local path is for the binary only. A record of what built a run (the
kernel-config registry's sources) names the reference instead, through
`restore_hf_references`, so it reads the same on every machine.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

HF_SCHEME = "hf://"

_REFERENCE = re.compile(r"^hf://(?P<repo>[^@/]+/[^@/]+)@(?P<revision>[0-9a-f]{7,40})/(?P<path>.+)$")


# The reference each local path this process resolved came from.
_RESOLVED: dict[str, str] = {}


class CorpusError(RuntimeError):
    """A reference that cannot be parsed or fetched."""


def _download(repo: str, revision: str, path: str) -> Path:
    from huggingface_hub import hf_hub_download

    return Path(hf_hub_download(repo_id=repo, filename=path, revision=revision))


def _cached(repo: str, revision: str, path: str) -> Path:
    """`_download` without the network: the file the local hub cache holds."""
    from huggingface_hub import try_to_load_from_cache

    local = try_to_load_from_cache(repo_id=repo, filename=path, revision=revision)
    if not isinstance(local, str):
        raise FileNotFoundError(f"{repo}@{revision}/{path} is not in the local hub cache")
    return Path(local)


def resolve_reference(reference: str, *, local_only: bool = False) -> str:
    """Fetch one `hf://` reference and return the local path it resolved to.

    A token corpus manifest names its payload in `data_file`, relative to
    itself, so that file is fetched too -- the hub's snapshot layout mirrors the
    repository, which puts the two back in one directory.

    `local_only` never reaches the network: a reference whose files the local
    hub cache does not already hold raises `CorpusError`.
    """
    match = _REFERENCE.match(reference)
    if not match:
        raise CorpusError(
            f"{reference!r} is not hf://<owner>/<repo>@<commit-sha>/<path>; "
            "a revision is required and must be a commit sha, not a branch or tag"
        )
    repo, revision, path = match["repo"], match["revision"], match["path"]
    fetch = _cached if local_only else _download
    try:
        local = fetch(repo, revision, path)
    except Exception as exc:  # noqa: BLE001 — the hub raises a wide family
        raise CorpusError(f"fetching {reference}: {exc}") from exc

    if local.name.endswith(".json"):
        try:
            data_file = json.loads(local.read_text()).get("data_file")
        except json.JSONDecodeError as exc:
            raise CorpusError(f"{reference} is not readable JSON: {exc}") from exc
        if isinstance(data_file, str) and data_file:
            try:
                payload = fetch(repo, revision, str(Path(path).parent / data_file))
            except Exception as exc:  # noqa: BLE001 — as above
                raise CorpusError(f"fetching {reference}'s {data_file}: {exc}") from exc
            # The loader resolves `data_file` against the manifest's directory,
            # so that is where the hub must have put it -- a subdirectory too.
            if payload != local.parent / data_file:
                raise CorpusError(
                    f"{reference}: the hub placed {data_file} at {payload}, "
                    f"not where its manifest in {local.parent} names it"
                )
    _RESOLVED[str(local)] = reference
    return str(local)


def resolve_hf_references(config):
    """Replace every `hf://` string leaf in an expanded config with its file.

    Applied to the whole tree rather than to named keys: the scheme is
    unambiguous, and an artifact field that gains hub hosting later should not
    need this module edited to work.
    """
    if isinstance(config, dict):
        return {key: resolve_hf_references(value) for key, value in config.items()}
    if isinstance(config, list):
        return [resolve_hf_references(value) for value in config]
    if isinstance(config, str) and config.startswith(HF_SCHEME):
        return resolve_reference(config)
    return config


def restore_hf_references(config):
    """The config as its preset wrote it: every string leaf that is a path this
    process resolved a reference to becomes that reference again."""
    if isinstance(config, dict):
        return {key: restore_hf_references(value) for key, value in config.items()}
    if isinstance(config, list):
        return [restore_hf_references(value) for value in config]
    if isinstance(config, str):
        return _RESOLVED.get(config, config)
    return config
