"""Wrap an annotated vLLM launch under rocprofv3 and produce a rocpd database.

The AMD counterpart of ``alignment/profiler/nsys_capture.py``. Where nsys runs
``nsys profile [flags] <server argv>`` and exports a ``.sqlite``, rocprofv3 runs
``rocprofv3 [flags] -- <server argv>`` and writes a rocpd SQLite database
directly — so there is no separate export step. The flags that matter for
alignment:

- ``--kernel-trace`` records every GPU kernel dispatch (the rows
  ``profiling.profilers.rocprof_kernel_profiler.kernel_dispatch_records_from_rocpd``
  reads and the producer attributes to iterations).
- ``--marker-trace`` records the roctx ranges the
  :mod:`alignment.profiler.roctx_shim` shim emits — the ``vllm_iteration(N):
  <phase>`` iteration windows the timestamp-containment join owns dispatches by.
- ``--output-format rocpd`` selects the SQLite form the readers understand.

``--kernel-trace`` is the AMD analog of nsys's ``--cuda-graph-trace=node``: it is
mandatory, because without it a trace can carry roctx ranges and still hold no
GPU dispatch rows. The eager (no-HIP-graph) path does not need host HIP-API
correlation, so ``--hip-trace`` is off by default; HIP-graph correlation
ownership is a later chunk.

The executable, output directory, and output name are parameters, never
hardcoded — the 8-GPU orchestrator passes a per-rank output path. The subprocess
is the only GPU-touching step; it is injectable so the capture assembly and the
rocpd validation are unit-testable on-host without rocprofv3 or a GPU.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from ..rocpd import parse as rocpd_parse
from ..rocpd.evidence import (
    is_sentinel_dispatch,
    iteration_regions,
    sentinel_iteration_regions,
)
from .config import RocprofConfig
from .roctx_shim import RANK_PID_DIR_ENV, ROCTX_SCOPES_ENV

try:  # the readers live in the profiling package (C0)
    from profiling.profilers.rocprof_kernel_profiler import (
        kernel_dispatch_records_from_rocpd,
        roctx_regions_from_rocpd,
    )
except Exception:  # pragma: no cover - import shape guarded; validate() re-raises
    kernel_dispatch_records_from_rocpd = None  # type: ignore[assignment]
    roctx_regions_from_rocpd = None  # type: ignore[assignment]

#: How a rocpd output is named/placed. rocprofv3 writes ``<dir>/<name>_results.db``
#: for ``--output-format rocpd`` (older builds used ``<name>.db``); the locator
#: accepts either so a version bump does not silently break discovery.
_ROCPD_SUFFIXES = ("_results.db", ".db")

#: vLLM runs the V1 engine (and the model) in a SEPARATE ``EngineCore`` process by
#: default, so a rocprofv3 capture that wraps only the launcher traces the launcher
#: and never sees the engine's kernel dispatches. Setting this to ``"0"`` puts the
#: engine in-process with the launcher, so the single wrapped process carries the
#: GPU work -- the fix that let the 1-GPU validation capture any dispatches at all.
#: It is a DEFAULT (``setdefault``), so an operator who needs the multiprocessing
#: engine (and per-rank tracing instead) can still override it in the base env.
VLLM_V1_MULTIPROCESSING_ENV = "VLLM_ENABLE_V1_MULTIPROCESSING"

#: The env var each worker process carries its rank in, used to template a
#: per-rank rocprofv3 output name for TP>1, so each of the N workers writes a
#: distinct ``<name>_rank<N>_results.db``. NOTE: vLLM's V1 offline
#: ``LLM(tensor_parallel_size=N)`` MultiprocExecutor does NOT export this (it
#: passes each worker its rank as a constructor kwarg, not an env var — only the
#: Ray path calls ``update_environment_variables``). The ``roctx_shim`` stamps the
#: worker's global rank into ``RANK`` (and ``LOCAL_RANK``) on the first forward,
#: which rocprofv3 — resolving ``%q{ENV}%`` at output-finalize time — picks up when
#: it writes the per-process rocpd. It is configurable in case a future stack
#: populates a different var.
OUTPUT_RANK_ENV_DEFAULT = "RANK"

#: Body of the generated ``sitecustomize.py`` prepended to the launched server's
#: PYTHONPATH. Python imports ``sitecustomize`` automatically at interpreter
#: startup — before any user/torch import — so this is the earliest in-process
#: hook that can RTLD_GLOBAL-load the SDK roctx library before torch pulls in
#: legacy ``libroctx64`` (the Gap-2 load-order fix; see ``_roctx_preload`` and
#: ``ROCM_CAPTURE_VALIDATION.md``). It is gated internally on
#: ``VLLM_ROCTX_SCOPES_FOR_PROFILING`` and swallows all errors so a server launch
#: is never taken down by the preloader. If the alignment package is not importable
#: in the serving venv the preload is simply skipped (the shim still falls back to
#: a runtime dlopen).
_SITECUSTOMIZE_BODY = """\
# Generated by alignment.profiler.rocprof_capture — do not edit.
# Runs at interpreter startup, before torch, to preload the rocprofiler-sdk roctx
# library RTLD_GLOBAL so rocprofv3 --marker-trace's MARKER service wins over the
# legacy libroctx64 that torch/aiter load later. Gated + error-tolerant inside.
try:
    from alignment.profiler._roctx_preload import preload_sdk_roctx

    preload_sdk_roctx()
except Exception:  # pragma: no cover - startup hook must never crash the server
    pass
"""


def write_roctx_sitecustomize(sc_dir: Path) -> Path:
    """Write the roctx-preload ``sitecustomize.py`` into ``sc_dir`` and return it."""
    sc_dir.mkdir(parents=True, exist_ok=True)
    (sc_dir / "sitecustomize.py").write_text(_SITECUSTOMIZE_BODY)
    return sc_dir


def write_roctx_sitecustomize_dir(parent: Path | None = None) -> Path:
    """Write a ``sitecustomize.py`` roctx preloader into a fresh dir and return it.

    The returned directory is meant to be prepended to the launched server's
    ``PYTHONPATH`` so its ``sitecustomize.py`` runs before torch. ``parent`` places
    the dir under a known root (e.g. the capture output dir); the default creates a
    throwaway temp dir. The generated hook is self-gating on the roctx env flag, so
    the dir is harmless if the flag is later unset.
    """
    if parent is not None:
        parent.mkdir(parents=True, exist_ok=True)
    sc_dir = Path(tempfile.mkdtemp(prefix="vibesim-roctx-", dir=parent))
    return write_roctx_sitecustomize(sc_dir)

#: Recovers the integer rank from a per-rank rocpd filename written by the
#: templated ``-o`` (``<name>_rank<N>_results.db`` / ``<name>_rank<N>.db``).
_RANK_FROM_FILENAME_RE = re.compile(r"_rank(\d+)(?:_results)?\.db$")

#: Recovers the OS pid from a per-process rocpd filename the tool-env path writes
#: with the ``%pid%`` placeholder (``<name>_pid<PID>_results.db`` / ``<name>_pid<PID>.db``).
#: rocprofiler-sdk always resolves ``%pid%`` (unlike ``%q{RANK}%``, which expands at
#: process start before vLLM's MultiprocExecutor stamps the worker rank), so naming by
#: pid and attributing rank from a sidecar afterwards is the collision-free mechanism.
_PID_FROM_FILENAME_RE = re.compile(r"_pid(\d+)(?:_results)?\.db$")

#: How a TP>1 per-rank capture attaches the profiler to the worker processes.
#:
#: ``ATTACH_MODE_WRAP`` is the original mechanism: one ``rocprofv3`` CLI wraps the
#: whole launcher process tree, and the inherited rocprofiler-sdk tool traces every
#: process, each writing its own ``%q{RANK}%`` rocpd on a clean exit. This is sound
#: ONLY when no process that receives vLLM's teardown SIGTERM owns worker children.
#: On vLLM V1 with a separate ``EngineCore`` process (``VLLM_ENABLE_V1_MULTIPROCESSING=1``)
#: it DEADLOCKS: at shutdown vLLM SIGTERMs ``EngineCore``; rocprofv3's
#: ``error_signal_handler`` catches signal 15 inside ``EngineCore`` and blocks
#: ("will wait for N children to exit") because its TP workers have not been told to
#: stop; vLLM force-kills ``EngineCore`` after its grace window, before any worker
#: finalizes, so ZERO per-rank databases land. (Confirmed on rocprofv3 1.3.2 / ROCm
#: 7.2.3.) The wrap mode therefore requires the engine in-process
#: (``VLLM_ENABLE_V1_MULTIPROCESSING=0``), which :func:`build_capture_server_env`
#: already defaults, so the only process holding worker children (the launcher) is
#: the rocprofv3 root itself and tears the executor down without a cross-process
#: SIGTERM.
#:
#: ``ATTACH_MODE_TOOL_ENV`` removes the wrapping CLI entirely and injects the
#: rocprofiler-sdk tool through the rocprofiler-REGISTER path only. ``rocprofv3``
#: injects its tool TWO ways at once (observed on rocprofv3 1.3.2 / ROCm 7.2.3): an
#: ``LD_PRELOAD`` of ``librocprofiler-sdk-tool.so`` AND ``ROCP_TOOL_LIBRARIES``.
#: ``LD_PRELOAD`` loads the tool UNCONDITIONALLY in every process (parent, EngineCore,
#: workers) at process start — reinstating the exact teardown deadlock (the preloaded
#: tool's signal handler fires in EngineCore and blocks on its worker children) — and,
#: with ``ROCPROFILER_LIBRARY_CTOR=1``, expands ``%q{RANK}%`` at process start before
#: the worker's rank is known. So this mode DROPS ``LD_PRELOAD`` and keeps only
#: ``ROCP_TOOL_LIBRARIES`` (+ the ``ROCPROFILER_REGISTER_LIBRARY`` register lib):
#: rocprofiler-register loads the tool lazily when the ROCm runtime initializes, which
#: happens only in the GPU worker processes and only AFTER the worker has set ``RANK``.
#: The pure-Python ``EngineCore`` and driver never initialize the runtime, so they
#: never load the tool, the teardown SIGTERM reaches only handler-free processes,
#: vLLM's orderly shutdown runs, and each worker resolves ``%q{RANK}%`` and finalizes
#: its own per-rank rocpd on its own clean exit. This is the mechanism for a true
#: multiprocessing TP>1 capture.
ATTACH_MODE_WRAP = "wrap"
ATTACH_MODE_TOOL_ENV = "tool-env"
ATTACH_MODES = (ATTACH_MODE_WRAP, ATTACH_MODE_TOOL_ENV)

#: The environment keys that carry rocprofiler-sdk tool configuration. Only these
#: are lifted out of a harvest of what ``rocprofv3`` injects, so unrelated process
#: env (``PWD``, ``SHLVL``, ``_`` …) never leaks into the launched server. Matched by
#: prefix because the ``ROCPROF_*`` trace/output surface is open-ended and a version
#: bump may add or rename a knob — harvesting rather than hardcoding keeps a renamed
#: knob from being silently dropped. Covers the tool-library selector
#: (``ROCP_TOOL_LIBRARIES``; legacy ``HSA_TOOLS_LIB``), the loader preload
#: (``LD_PRELOAD``), and the ``ROCPROF*``/``ROCPROFILER*`` trace+output knobs.
_TOOL_ENV_KEY_RE = re.compile(r"^(ROCP_|ROCPROF|HSA_TOOLS_LIB|LD_PRELOAD|ROCPROFILER)")

#: The harvested key whose VALUE selects the rocprofiler-sdk tool library by the
#: rocprofiler-register path. It must come from the harvest (the absolute library
#: path is stack- and version-specific), and it is what makes the ROCm runtime load
#: the tool lazily at init — in the GPU workers only — rather than at process start.
_TOOL_LIBRARIES_KEY = "ROCP_TOOL_LIBRARIES"

#: Harvested keys that are DROPPED from the injected env. ``LD_PRELOAD`` would load
#: the tool unconditionally in every process (reinstating the EngineCore teardown
#: deadlock and expanding ``%q{RANK}%`` before the rank is set), which is exactly what
#: the rocprofiler-register path exists to avoid. A pre-existing ``LD_PRELOAD`` in the
#: base env is preserved untouched; only rocprofv3's harvested one is dropped.
_TOOL_ENV_DROP_KEYS = ("LD_PRELOAD",)

Runner = Callable[[list[str]], subprocess.CompletedProcess]


def per_rank_output_name(
    output_name: str, rank_env: str = OUTPUT_RANK_ENV_DEFAULT
) -> str:
    """Template a per-rank rocprofv3 ``-o`` name for a TP>1 capture.

    rocprofv3 expands a ``%q{ENV}%`` key in the output name to that environment
    variable's value *in each traced process*, so one wrapped launch of an N-way
    tensor-parallel server yields one rocpd database per worker:
    ``<name>_rank0_results.db`` ... ``<name>_rank{N-1}_results.db``. This is the
    ``-o rank{n}`` style the runbook anticipates, expressed through the rocprofv3
    placeholder so the tool -- not this driver -- stamps each worker's own rank.
    """
    return f"{output_name}_rank%q{{{rank_env}}}%"


def rank_from_rocpd_path(db_path: Path) -> int | None:
    """Parse the worker rank out of a per-rank rocpd filename, or ``None``."""
    match = _RANK_FROM_FILENAME_RE.search(db_path.name)
    return int(match.group(1)) if match else None


def per_pid_output_name(output_name: str) -> str:
    """Template a per-process rocprofv3 ``-o`` name keyed by OS pid.

    rocprofiler-sdk resolves the ``%pid%`` placeholder in every traced process
    (always, and uniquely), so an N-way tensor-parallel server writes one database
    per worker — ``<name>_pid<PID>_results.db`` — with no filename collision. This
    replaces the ``%q{RANK}%`` template for the tool-env path, where the rank env is
    not yet set when rocprofiler-sdk expands the output name at runtime init; rank is
    recovered afterwards from the shim's pid->rank sidecars (:func:`_attribute_pid_dbs_to_ranks`).
    """
    return f"{output_name}_pid%pid%"


def pid_from_rocpd_path(db_path: Path) -> int | None:
    """Parse the OS pid out of a per-process rocpd filename, or ``None``."""
    match = _PID_FROM_FILENAME_RE.search(db_path.name)
    return int(match.group(1)) if match else None


def _read_pid_rank_sidecars(pidrank_dir: Path) -> dict[int, int]:
    """Read the ``<pid>.rank`` sidecars the roctx shim drops, as ``{pid: rank}``.

    The shim writes one file per GPU worker (see
    :func:`roctx_shim.write_rank_pid_sidecar`) once it learns its rank on the first
    forward. A malformed or non-numeric sidecar is skipped rather than aborting the
    whole attribution.
    """
    mapping: dict[int, int] = {}
    if not pidrank_dir.is_dir():
        return mapping
    for sidecar in pidrank_dir.glob("*.rank"):
        try:
            pid = int(sidecar.stem)
            rank = int(sidecar.read_text().strip())
        except (ValueError, OSError):
            continue
        mapping[pid] = rank
    return mapping


def _attribute_pid_dbs_to_ranks(
    output_dir: Path, output_name: str, pidrank_dir: Path
) -> list[Path]:
    """Rename each ``%pid%``-named rocpd to its ``_rank<N>`` filename, in rank order.

    Joins the per-process databases a tool-env capture wrote
    (``<name>_pid<PID>{suffix}``) to the shim's pid->rank sidecars and renames each to
    the ``<name>_rank<N>{suffix}`` spelling the merge pipeline keys rank on
    (``rocpd/merge.py`` parses ``rank(\\d+)`` from the filename). Raises when no
    per-process database exists (a capture that traced no worker), or when a database
    has no matching sidecar (the shim never stamped that worker's rank — attributing it
    to a guessed rank would be fabricated data, so refuse loudly instead).
    """
    pid_rank = _read_pid_rank_sidecars(pidrank_dir)
    renamed: list[tuple[int, Path]] = []
    seen: set[Path] = set()
    for suffix in _ROCPD_SUFFIXES:
        for candidate in sorted(output_dir.glob(f"{output_name}_pid*{suffix}")):
            if candidate in seen:
                continue
            pid = pid_from_rocpd_path(candidate)
            if pid is None:
                continue
            seen.add(candidate)
            if pid not in pid_rank:
                raise RuntimeError(
                    f"rocpd {candidate.name} has no pid->rank sidecar in {pidrank_dir} "
                    f"(sidecars present: {sorted(pid_rank)}); the roctx shim never stamped "
                    "this worker's rank, so its rank cannot be attributed without guessing"
                )
            rank = pid_rank[pid]
            target = output_dir / f"{output_name}_rank{rank}{suffix}"
            candidate.rename(target)
            renamed.append((rank, target))
    if not renamed:
        raise FileNotFoundError(
            f"no per-process rocpd databases for output name {output_name!r} under "
            f"{output_dir} (looked for {output_name}_pid<PID>{_ROCPD_SUFFIXES})"
        )
    renamed.sort(key=lambda item: item[0])
    return [path for _, path in renamed]


@dataclass(frozen=True)
class ResolvedRocprofExecutable:
    """One verified rocprofv3 binary, with its reported version for provenance."""

    path: Path
    version: str

    def provenance(self) -> dict[str, str]:
        return {"executable": str(self.path), "version": self.version}


def resolve_rocprof_executable(configured_path: str | None) -> ResolvedRocprofExecutable:
    """Resolve and verify the exact rocprofv3 binary from config or ``ROCPROF_BIN``.

    Mirrors ``resolve_nsys_executable``: an absolute path is required (the profiler
    version is run provenance, so PATH guessing is refused), the file must be
    executable, and ``--version`` must return a non-empty string.
    """
    selected_path = configured_path or os.environ.get("ROCPROF_BIN")
    if not selected_path:
        raise ValueError(
            "rocprofv3 executable is not configured; set rocprof.executable or "
            "ROCPROF_BIN to the exact rocprofv3 executable"
        )
    executable_path = Path(selected_path).expanduser()
    if not executable_path.is_absolute():
        raise ValueError(f"rocprofv3 executable must be an absolute path: {selected_path}")
    try:
        executable_path = executable_path.resolve(strict=True)
    except FileNotFoundError as error:
        raise FileNotFoundError(f"rocprofv3 executable does not exist: {selected_path}") from error
    if not executable_path.is_file() or not os.access(executable_path, os.X_OK):
        raise PermissionError(f"rocprofv3 executable is not executable: {executable_path}")
    version_result = subprocess.run(
        [str(executable_path), "--version"],
        capture_output=True,
        text=True,
        check=True,
    )
    version = (version_result.stdout or version_result.stderr).strip()
    if not version:
        raise RuntimeError(f"rocprofv3 returned an empty version string: {executable_path}")
    return ResolvedRocprofExecutable(path=executable_path, version=version)


def build_rocprof_prefix(
    executable: ResolvedRocprofExecutable,
    config: RocprofConfig,
    output_dir: Path,
    output_name: str,
) -> list[str]:
    """The ``rocprofv3 ... --`` argv that prefixes the server command.

    The returned list ends with ``--``; the caller appends the server argv.
    """
    config.validate()
    prefix = [str(executable.path)]
    if config.kernel_trace:
        prefix.append("--kernel-trace")
    if config.marker_trace:
        prefix.append("--marker-trace")  # roctx iteration ranges
    if config.hip_trace:
        prefix.append("--hip-trace")
    prefix += [
        "--output-format",
        config.output_format,
        "-d",
        str(output_dir),
        "-o",
        output_name,
    ]
    prefix += list(config.extra_args)
    prefix.append("--")
    return prefix


def build_capture_server_env(
    base_env: dict[str, str] | None = None,
    *,
    sitecustomize_dir: Path | None = None,
) -> dict[str, str]:
    """The env for the launched server that guarantees the roctx shim fires.

    The AMD analog of what ``vllm_server.build_server_env`` does for NVTX: the
    capture driver — not the operator — turns the iteration annotation on, so a
    capture cannot silently record kernel dispatches with no
    ``vllm_iteration(N)`` roctx ranges to own them.

    vLLM already discovers and calls this package's ``vllm.general_plugins``
    entry point (:func:`roctx_shim.install_vllm_roctx_shim`) in every worker
    process; the plugin, however, no-ops unless :data:`ROCTX_SCOPES_ENV` is
    ``"1"``. Setting it here is the one thing that makes a real capture actually
    bracket each served forward. ``VLLM_PLUGINS`` is intentionally left untouched:
    stock vLLM loads all general plugins by default, so narrowing it would only
    risk disabling unrelated plugins. When a caller does set ``VLLM_PLUGINS`` in
    ``base_env``, it must already include
    :data:`roctx_shim.ROCTX_PLUGIN_ENTRY_POINT_NAME`.

    It also PREPENDS a generated ``sitecustomize.py`` dir to the server's
    ``PYTHONPATH`` (:func:`write_roctx_sitecustomize_dir`) so the SDK roctx library
    is RTLD_GLOBAL-loaded before torch imports legacy ``libroctx64`` — the Gap-2
    load-order fix. The driver's own ``PYTHONPATH`` is left untouched (the dir goes
    only onto the launched server's env); any existing server ``PYTHONPATH`` is
    preserved after the injected dir. Pass ``sitecustomize_dir`` to reuse a known
    dir instead of a throwaway temp one. The sitecustomize hook is itself gated on
    :data:`ROCTX_SCOPES_ENV`, so it no-ops if that flag is later unset.
    """
    env = dict(os.environ if base_env is None else base_env)
    env[ROCTX_SCOPES_ENV] = "1"
    # Put the V1 engine in-process so the wrapped process carries the GPU work.
    # setdefault, not assignment: an operator tracing the multiprocessing engine
    # per-rank (TP>1) can still override it in the base env.
    env.setdefault(VLLM_V1_MULTIPROCESSING_ENV, "0")
    # Prepend the roctx sitecustomize dir so the SDK roctx lib loads before torch.
    sc_dir = (
        write_roctx_sitecustomize(sitecustomize_dir)
        if sitecustomize_dir is not None
        else write_roctx_sitecustomize_dir()
    )
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = (
        os.pathsep.join([str(sc_dir), existing]) if existing else str(sc_dir)
    )
    return env


def build_capture_argv(
    executable: ResolvedRocprofExecutable,
    config: RocprofConfig,
    server_argv: list[str],
    output_dir: Path,
    output_name: str,
) -> list[str]:
    """The full ``rocprofv3 ... -- <server argv>`` command line."""
    if not server_argv:
        raise ValueError("server_argv must name the command to profile")
    return build_rocprof_prefix(executable, config, output_dir, output_name) + list(server_argv)


def locate_rocpd(output_dir: Path, output_name: str) -> Path:
    """Find the rocpd database rocprofv3 wrote for ``output_name`` under ``output_dir``.

    Accepts both the current ``<name>_results.db`` and the older ``<name>.db``
    spelling; raises when neither exists so a silent capture miss is not mistaken
    for an empty trace.
    """
    for suffix in _ROCPD_SUFFIXES:
        candidate = output_dir / f"{output_name}{suffix}"
        if candidate.exists():
            return candidate
    # rocprofv3 builds have also nested the db under <dir>/<name>/; accept a single
    # *.db there (name-scoped) before giving up.
    nested = sorted(output_dir.glob(f"{output_name}/*.db"))
    if nested:
        return nested[0]
    raise FileNotFoundError(
        f"no rocpd database for output name {output_name!r} under {output_dir} "
        f"(looked for {_ROCPD_SUFFIXES} and nested *.db)"
    )


def locate_rocpd_per_rank(output_dir: Path, output_name: str) -> list[Path]:
    """Find every per-rank rocpd database a TP>1 capture wrote, in rank order.

    The templated ``-o`` (see :func:`per_rank_output_name`) makes rocprofv3 stamp
    each worker's rank into its filename, so an N-way capture leaves
    ``<name>_rank0_results.db`` ... ``<name>_rank{N-1}_results.db`` under
    ``output_dir``. Returns them sorted by the parsed rank; raises when none exist
    so a capture that traced no worker is not mistaken for an empty trace.
    """
    found: list[tuple[int, Path]] = []
    for suffix in _ROCPD_SUFFIXES:
        for candidate in output_dir.glob(f"{output_name}_rank*{suffix}"):
            rank = rank_from_rocpd_path(candidate)
            if rank is not None and candidate not in (p for _, p in found):
                found.append((rank, candidate))
    if not found:
        raise FileNotFoundError(
            f"no per-rank rocpd databases for output name {output_name!r} under "
            f"{output_dir} (looked for {output_name}_rank<N>{_ROCPD_SUFFIXES})"
        )
    found.sort(key=lambda item: item[0])
    return [path for _, path in found]


def run_capture_per_rank(
    executable: ResolvedRocprofExecutable,
    config: RocprofConfig,
    server_argv: list[str],
    output_dir: Path,
    output_name: str,
    *,
    rank_env: str = OUTPUT_RANK_ENV_DEFAULT,
    env: dict[str, str] | None = None,
    runner: Runner = subprocess.run,
) -> list[Path]:
    """Run a TP>1 server under rocprofv3 and return every per-rank rocpd path.

    One wrapped launch traces the whole worker-process tree; the per-rank
    ``%q{ENV}%`` output template makes each worker write its own database, which
    :func:`locate_rocpd_per_rank` then collects. ``runner`` is injectable exactly
    as in :func:`run_capture` so the per-rank argv assembly and output discovery
    are unit-testable on-host without rocprofv3 or multiple GPUs.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    templated_name = per_rank_output_name(output_name, rank_env)
    argv = build_capture_argv(executable, config, server_argv, output_dir, templated_name)
    completed = runner(argv, env=env, check=True)  # type: ignore[call-arg]
    if getattr(completed, "returncode", 0) not in (0, None):
        raise RuntimeError(f"rocprofv3 exited with code {completed.returncode}")
    return locate_rocpd_per_rank(output_dir, output_name)


#: A runner that CAPTURES stdout, used to harvest the env ``rocprofv3`` injects.
#: Separate from :data:`Runner` (which streams), and injectable so the harvest is
#: unit-testable without the real binary.
ProbeRunner = Callable[..., subprocess.CompletedProcess]


def _default_probe_runner(argv: list[str], *, env: dict[str, str] | None, check: bool) -> subprocess.CompletedProcess:
    return subprocess.run(argv, env=env, check=check, capture_output=True, text=True)


def harvest_tool_env(
    executable: ResolvedRocprofExecutable,
    config: RocprofConfig,
    output_dir: Path,
    output_name: str,
    *,
    base_env: dict[str, str],
    probe_runner: ProbeRunner = _default_probe_runner,
    probe_argv: tuple[str, ...] = ("env",),
) -> dict[str, str]:
    """Return the rocprofiler-sdk tool env ``rocprofv3`` injects, by probing it.

    Runs ``rocprofv3 <flags> -d <dir> -o <output_name> -- env`` (the probe prints
    its own environment and exits immediately, so rocprofv3 finalizes a throwaway,
    kernel-less database) and diffs the probe's environment against ``base_env``.
    The keys that are new or changed AND match :data:`_TOOL_ENV_KEY_RE` are exactly
    the rocprofiler-sdk knobs — tool-library selector, loader preload, and
    ``ROCPROF_*`` trace/output configuration — that make the ROCm runtime load the
    tool in-process. ``output_name`` is passed through verbatim (templated with the
    per-rank ``%q{RANK}%`` key by the caller) so the harvested output configuration
    already carries the per-rank template each worker resolves for itself.

    Harvesting rather than hardcoding the key names keeps a rocprofv3 version bump
    that renames or adds a knob from silently dropping configuration.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    argv = build_capture_argv(executable, config, list(probe_argv), output_dir, output_name)
    completed = probe_runner(argv, env=base_env, check=True)
    text = getattr(completed, "stdout", "") or ""
    if isinstance(text, bytes):
        text = text.decode("utf-8", "replace")
    injected: dict[str, str] = {}
    for line in text.splitlines():
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        if not _TOOL_ENV_KEY_RE.match(key):
            continue
        if base_env.get(key) != value:
            injected[key] = value
    return injected


def tool_env_output_config(
    config: RocprofConfig, output_dir: Path, output_name_template: str
) -> dict[str, str]:
    """The explicit ``ROCPROF_*`` trace+output environment for a tool-env capture.

    Set from the capture config with the documented rocprofiler-sdk variable names
    (``ROCPROF_OUTPUT_PATH`` / ``ROCPROF_OUTPUT_FILE_NAME`` / ``ROCPROF_OUTPUT_FORMAT``
    and the per-trace toggles) rather than relying on rocprofv3 to export them, so
    each worker writes its own database under ``output_dir`` deterministically.
    ``output_name_template`` carries the per-process ``%pid%`` key the tool resolves
    for itself in each worker process (rank is attributed afterwards from sidecars).
    """
    env = {
        "ROCPROF_OUTPUT_FORMAT": config.output_format,
        "ROCPROF_OUTPUT_PATH": str(output_dir),
        "ROCPROF_OUTPUT_FILE_NAME": output_name_template,
    }
    if config.kernel_trace:
        env["ROCPROF_KERNEL_TRACE"] = "1"
    if config.marker_trace:
        # rocprofv3 1.3.2 spells the roctx/marker toggle ROCPROF_MARKER_API_TRACE
        # (confirmed by harvesting what the CLI injects); the sentinel path does not
        # depend on it, but keep it on so a roctx-recording stack also gets markers.
        env["ROCPROF_MARKER_API_TRACE"] = "1"
    if config.hip_trace:
        env["ROCPROF_HIP_API_TRACE"] = "1"
    return env


def run_capture_per_rank_tool_env(
    executable: ResolvedRocprofExecutable,
    config: RocprofConfig,
    server_argv: list[str],
    output_dir: Path,
    output_name: str,
    *,
    rank_env: str = OUTPUT_RANK_ENV_DEFAULT,
    env: dict[str, str] | None = None,
    runner: Runner = subprocess.run,
    probe_runner: ProbeRunner = _default_probe_runner,
) -> list[Path]:
    """Run a TP>1 server with the rocprofiler-sdk tool injected per-process by env.

    The :data:`ATTACH_MODE_TOOL_ENV` path: harvest the tool env rocprofv3 would
    export (:func:`harvest_tool_env`) for the per-rank templated output name, merge
    it into the server environment, and launch the server DIRECTLY — no wrapping
    rocprofv3 process. The ROCm runtime loads ``librocprofiler-sdk-tool.so``
    in-process only where it initializes (the GPU workers), each worker resolves the
    ``%q{RANK}%`` template and finalizes its own rocpd on a clean exit, and the
    teardown SIGTERM never reaches a profiler signal handler that owns worker
    children — so a separate ``EngineCore`` process no longer deadlocks the capture.

    ``runner`` runs the server (its argv is the server command, NOT a rocprofv3
    command); ``probe_runner`` runs the one-shot env harvest. Both are injectable so
    the whole path is unit-testable on-host without rocprofv3 or GPUs.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    base_env = dict(os.environ if env is None else env)
    # Name each worker's database by %pid% (always resolvable, unique) rather than
    # %q{RANK}% (empty at runtime init, before vLLM's MultiprocExecutor stamps the
    # rank — which collided every worker onto one filename). Rank is recovered after
    # the run from the shim's pid->rank sidecars and the files renamed to _rank<N>.
    templated_name = per_pid_output_name(output_name)
    injected = harvest_tool_env(
        executable,
        config,
        output_dir,
        templated_name,
        base_env=base_env,
        probe_runner=probe_runner,
    )
    if _TOOL_LIBRARIES_KEY not in injected:
        raise RuntimeError(
            f"tool-env attach harvested no {_TOOL_LIBRARIES_KEY} from rocprofv3 (got "
            f"{sorted(injected)}); this rocprofv3 build does not load its tool by the "
            "rocprofiler-register path, so the wrapping attach mode must be used instead"
        )
    server_env = dict(base_env)
    # Inject the harvested rocprofiler-sdk env EXCEPT the keys that would load the
    # tool unconditionally at process start (LD_PRELOAD): the rocprofiler-register
    # path (ROCP_TOOL_LIBRARIES) loads it lazily at ROCm-runtime init, so the tool
    # lands in the GPU workers only — not the EngineCore/driver — and after RANK is set.
    for key, value in injected.items():
        if key in _TOOL_ENV_DROP_KEYS:
            continue
        server_env[key] = value
    # Set the trace/output configuration explicitly (deterministic per-pid naming)
    # rather than trusting rocprofv3 to have exported it into the harvested child env.
    server_env.update(tool_env_output_config(config, output_dir, templated_name))
    # Point the roctx shim at a sidecar dir so each worker records its pid->rank once
    # it learns its rank; the driver reads these below to rename pid DBs to rank DBs.
    pidrank_dir = output_dir / f"{output_name}_pidrank"
    server_env[RANK_PID_DIR_ENV] = str(pidrank_dir)
    completed = runner(list(server_argv), env=server_env, check=True)  # type: ignore[call-arg]
    if getattr(completed, "returncode", 0) not in (0, None):
        raise RuntimeError(f"server exited with code {completed.returncode}")
    return _attribute_pid_dbs_to_ranks(output_dir, output_name, pidrank_dir)


def validate_rocpd(db_path: Path) -> dict:
    """Sanity-check a fresh rocpd against the iteration-marker + dispatch contract.

    Mirrors ``nsys_capture.validate_export``: catch the two failure modes before a
    confusing empty alignment —

    - no iteration markers → the shim did not run (env gate off / plugin not
      installed), OR both marker sources are missing;
    - no kernel dispatch rows → ``--kernel-trace`` never recorded GPU work.

    Iteration markers come from either source the producer accepts, roctx-first:
    the ``(vllm|sglang)_iteration(N)`` roctx ranges, or — when the stack does not
    record roctx (the Option-B case) — the ``vibesim_sentinel`` marker kernels in
    the dispatch trace. ``iteration_source`` records which one was found. Uses the
    real C0 readers, so a passing validation means the same rows the offline
    producer will attribute are present.
    """
    if roctx_regions_from_rocpd is None or kernel_dispatch_records_from_rocpd is None:
        raise RuntimeError(
            "profiling.profilers.rocprof_kernel_profiler is not importable; cannot "
            "read the rocpd capture"
        )
    regions = roctx_regions_from_rocpd(str(db_path))
    iters = iteration_regions(regions)
    all_dispatches = kernel_dispatch_records_from_rocpd(str(db_path))
    sentinels = [d for d in all_dispatches if is_sentinel_dispatch(d)]
    dispatches = [d for d in all_dispatches if not is_sentinel_dispatch(d)]
    if iters:
        iteration_source = "roctx"
    elif sentinels:
        iters = sentinel_iteration_regions(sentinels, dispatches)
        iteration_source = "sentinel"
    else:
        iteration_source = "none"
    starts = [region.start_ns for _, _, region in iters]
    ends = [region.end_ns for _, _, region in iters]
    span_ms = ((max(ends) - min(starts)) / 1e6) if iters else 0.0
    return {
        "iteration_ranges": len(iters),
        "iteration_source": iteration_source,
        "sentinel_kernels": len(sentinels),
        "kernel_rows": len(dispatches),
        "iteration_span_ms": span_ms,
        "ok": bool(iters) and bool(dispatches),
    }


def run_capture(
    executable: ResolvedRocprofExecutable,
    config: RocprofConfig,
    server_argv: list[str],
    output_dir: Path,
    output_name: str,
    *,
    env: dict[str, str] | None = None,
    runner: Runner = subprocess.run,
) -> Path:
    """Run the annotated server under rocprofv3 and return the produced rocpd path.

    ``runner`` defaults to :func:`subprocess.run` and is injectable so a test can
    stand in for the GPU subprocess (writing a synthetic rocpd) without the real
    binary. The output directory is created first because rocprofv3 does not.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    argv = build_capture_argv(executable, config, server_argv, output_dir, output_name)
    completed = runner(argv, env=env, check=True)  # type: ignore[call-arg]
    if getattr(completed, "returncode", 0) not in (0, None):
        raise RuntimeError(f"rocprofv3 exited with code {completed.returncode}")
    return locate_rocpd(output_dir, output_name)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="alignment rocpd-capture",
        description=(
            "Run an annotated vLLM command under rocprofv3, producing a rocpd "
            "database, then (unless --no-parse) run the offline rocpd->Check-1 "
            "producer on it. The command to profile follows a literal '--'."
        ),
    )
    parser.add_argument(
        "--rocprof",
        dest="rocprof",
        default=None,
        help="absolute path to the rocprofv3 executable (else ROCPROF_BIN)",
    )
    parser.add_argument("--output-dir", type=Path, required=True, help="rocpd output directory")
    parser.add_argument(
        "--output-name", required=True, help="rocpd output name (rocprofv3 -o stem)"
    )
    parser.add_argument("--hip-trace", action="store_true", help="also collect the HIP API stream")
    parser.add_argument(
        "--tp-size",
        type=int,
        default=1,
        help=(
            "tensor-parallel ranks the server spawns; >1 captures each worker "
            "process to its own per-rank rocpd database (-o <name>_rank<N>)"
        ),
    )
    parser.add_argument(
        "--rank-env",
        default=OUTPUT_RANK_ENV_DEFAULT,
        help="env var each worker carries its rank in, for the per-rank -o template",
    )
    parser.add_argument(
        "--attach-mode",
        choices=ATTACH_MODES,
        default=ATTACH_MODE_WRAP,
        help=(
            "how a TP>1 capture attaches the profiler: 'wrap' runs one rocprofv3 "
            "around the launcher (needs the engine in-process); 'tool-env' injects "
            "the rocprofiler-sdk tool env per-process so a separate EngineCore does "
            "not deadlock teardown (the robust multiprocessing-TP mechanism)"
        ),
    )
    parser.add_argument(
        "--rocprof-arg",
        dest="rocprof_args",
        action="append",
        default=[],
        help="extra rocprofv3 flag, repeatable; appended before '--'",
    )
    parser.add_argument(
        "--parsed-output",
        type=Path,
        default=None,
        help="write parsed.json (+ parsed.kernels.parquet) here after capture",
    )
    parser.add_argument(
        "--sequences-output",
        type=Path,
        default=None,
        help="also write the folded label-ready kernel-sequence catalog here",
    )
    parser.add_argument(
        "--iteration-start", type=int, default=None, help="first iteration index to keep"
    )
    parser.add_argument(
        "--iteration-end", type=int, default=None, help="last iteration index to keep"
    )
    parser.add_argument("--default-stage", default="all", help="stage for ranges lacking one")
    parser.add_argument(
        "--no-parse",
        action="store_true",
        help="only capture + validate the rocpd; skip the parse step",
    )
    return parser


def _split_command(argv: list[str]) -> tuple[list[str], list[str]]:
    """Split ``<capture flags> -- <server argv>`` on the first literal ``--``."""
    if "--" not in argv:
        raise SystemExit(
            "rocpd-capture requires the command to profile after a literal '--', e.g. "
            "rocpd-capture --output-dir D --output-name N -- python -m vllm ... serve ..."
        )
    cut = argv.index("--")
    return argv[:cut], argv[cut + 1 :]


def main(
    argv: list[str] | None = None,
    *,
    resolver: Callable[[str | None], ResolvedRocprofExecutable] = resolve_rocprof_executable,
    runner: Runner = subprocess.run,
    probe_runner: ProbeRunner = _default_probe_runner,
) -> int:
    """`alignment rocpd-capture` entry point.

    ``resolver`` / ``runner`` / ``probe_runner`` are injectable so the capture
    assembly, the tool-env harvest, rocpd validation, and the parse chain can be
    exercised on-host with the rocprofv3 binary and GPU subprocess stood in for;
    production uses the real defaults.
    """
    import sys

    flags, server_argv = _split_command(list(sys.argv[1:] if argv is None else argv))
    args = build_parser().parse_args(flags)
    if not server_argv:
        raise SystemExit("no command to profile after '--'")

    executable = resolver(args.rocprof)
    config = RocprofConfig(
        executable=str(executable.path),
        hip_trace=args.hip_trace,
        tp_size=args.tp_size,
        extra_args=list(args.rocprof_args),
        analyze_iteration_start=args.iteration_start,
        analyze_iteration_end=args.iteration_end,
    )
    capture_env = build_capture_server_env()

    if config.tp_size > 1:
        if args.attach_mode == ATTACH_MODE_TOOL_ENV:
            db_paths = run_capture_per_rank_tool_env(
                executable,
                config,
                server_argv,
                args.output_dir,
                args.output_name,
                rank_env=args.rank_env,
                env=capture_env,
                runner=runner,
                probe_runner=probe_runner,
            )
        else:
            db_paths = run_capture_per_rank(
                executable,
                config,
                server_argv,
                args.output_dir,
                args.output_name,
                rank_env=args.rank_env,
                env=capture_env,
                runner=runner,
            )
        overall = 0
        for db_path in db_paths:
            rank = rank_from_rocpd_path(db_path)
            report = validate_rocpd(db_path)
            print(
                json.dumps(
                    {"rank": rank, "rocpd": str(db_path), "validation": report},
                    separators=(",", ":"),
                )
            )
            if not report["ok"]:
                print(
                    f"rocpd capture for rank {rank} incomplete: need both iteration "
                    "roctx ranges and kernel dispatch rows (see validation above)",
                    file=sys.stderr,
                )
                overall = 1
                continue
            if args.no_parse:
                continue
            rc = rocpd_parse.main(
                _parse_argv_for(args, db_path, _rank_suffixed(args.parsed_output, rank),
                                _rank_suffixed(args.sequences_output, rank))
            )
            overall = overall or rc
        return overall

    db_path = run_capture(
        executable,
        config,
        server_argv,
        args.output_dir,
        args.output_name,
        env=capture_env,
        runner=runner,
    )
    report = validate_rocpd(db_path)
    print(json.dumps({"rocpd": str(db_path), "validation": report}, separators=(",", ":")))
    if not report["ok"]:
        print(
            "rocpd capture incomplete: need both iteration roctx ranges and kernel "
            "dispatch rows (see validation above)",
            file=sys.stderr,
        )
        return 1
    if args.no_parse:
        return 0

    return rocpd_parse.main(
        _parse_argv_for(args, db_path, args.parsed_output, args.sequences_output)
    )


def _rank_suffixed(path: Path | None, rank: int | None) -> Path | None:
    """Insert ``.rank<N>`` before the suffix of a per-rank output path.

    ``parsed.json`` -> ``parsed.rank0.json`` so each TP worker's parse lands in a
    distinct file. ``None`` (no such output requested) stays ``None``.
    """
    if path is None or rank is None:
        return path
    return path.with_suffix(f".rank{rank}{path.suffix}")


def _parse_argv_for(
    args: argparse.Namespace,
    db_path: Path,
    parsed_output: Path | None,
    sequences_output: Path | None,
) -> list[str]:
    """Assemble the ``rocpd-parse`` argv for one captured database."""
    parse_argv = ["--db", str(db_path), "--default-stage", args.default_stage]
    if args.iteration_start is not None:
        parse_argv += ["--iteration-start", str(args.iteration_start)]
    if args.iteration_end is not None:
        parse_argv += ["--iteration-end", str(args.iteration_end)]
    if parsed_output is not None:
        parse_argv += ["--output", str(parsed_output)]
    if sequences_output is not None:
        parse_argv += ["--sequences-output", str(sequences_output)]
    return parse_argv


if __name__ == "__main__":
    raise SystemExit(main())
