//! Pending-request selection policy.
//!
//! A policy owns queue membership and ordering. Admission lifecycles freeze the
//! immutable ranking facts once, at enqueue time, then use `peek` to test the
//! selected request against token/KV gates. A rejected head stays queued.

use crate::common::{RequestId, SessionInput, Time};

mod fifo;
mod session_start;
mod shortest_job_first;

pub use fifo::FifoOrder;
pub use session_start::SessionStartOrder;
pub use shortest_job_first::ShortestJobFirst;

/// Immutable facts available to a pending-order policy.
///
/// `enqueue_sequence` is generated by the admission instance, rather than copied
/// from simulated time: multiple requests may arrive at the same timestamp and
/// still require a deterministic FIFO tie-break.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AdmissionCandidate {
    pub request_id: RequestId,
    pub enqueue_sequence: u64,
    pub fresh_prompt_tokens: u32,
    pub remaining_output_tokens: u32,
    pub session_input: SessionInput,
    /// Trace-declared session start, or actual arrival when this request is a
    /// standalone one-request conversation.
    pub conversation_start_time: Time,
}

impl AdmissionCandidate {
    #[inline]
    pub fn queued_kv_tokens(self) -> u64 {
        u64::from(self.fresh_prompt_tokens)
            + u64::from(self.session_input.declared_prefix_tokens())
            + u64::from(self.remaining_output_tokens)
    }
}

/// Per-admission monotonic sequence used for stable policy tie-breaking.
#[derive(Default)]
pub(crate) struct EnqueueSequence {
    next: u64,
}

impl EnqueueSequence {
    pub(crate) fn freeze(
        &mut self,
        request_id: RequestId,
        fresh_prompt_tokens: u32,
        remaining_output_tokens: u32,
        session_input: SessionInput,
        conversation_start_time: Time,
    ) -> AdmissionCandidate {
        let enqueue_sequence = self.next;
        self.next = self
            .next
            .checked_add(1)
            .expect("admission enqueue sequence overflow");
        AdmissionCandidate {
            request_id,
            enqueue_sequence,
            fresh_prompt_tokens,
            remaining_output_tokens,
            session_input,
            conversation_start_time,
        }
    }
}

/// Owns the pending set and selects one stable head for the lifecycle to gate.
pub trait PendingOrderPolicy {
    type Context;

    fn push(&mut self, candidate: AdmissionCandidate, context: &mut Self::Context);
    fn peek(&self) -> Option<AdmissionCandidate>;
    fn pop(&mut self, context: &mut Self::Context) -> Option<AdmissionCandidate>;
    fn remove(&mut self, request: RequestId) -> Option<AdmissionCandidate>;
    fn contains(&self, request: RequestId) -> bool;
    fn len(&self) -> usize;
    fn queued_kv_tokens(&self) -> u64;

    #[inline]
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}
