//! Pending-request selection policy.
//!
//! A policy owns queue membership and ordering. Admission lifecycles freeze the
//! immutable ranking facts once, at enqueue time, then use `peek` to test the
//! selected request against token/KV gates. A rejected head stays queued.

use crate::common::{PrefixInput, RequestId, Time};

mod fifo;
mod shortest_job_first;

pub use fifo::FifoOrder;
pub use shortest_job_first::ShortestJobFirst;

/// Immutable facts available to a pending-order policy.
///
/// `enqueue_sequence` is generated by the admission instance, rather than copied
/// from simulated time: multiple requests may arrive at the same timestamp and
/// still require a deterministic FIFO tie-break.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AdmissionCandidate {
    pub request: RequestId,
    pub enqueue_sequence: u64,
    pub prompt: u32,
    pub decode: u32,
    pub prefix: PrefixInput,
    pub deadline: Option<Time>,
    pub matched_tokens: u32,
}

impl AdmissionCandidate {
    #[inline]
    pub fn queued_kv_tokens(self) -> u64 {
        u64::from(self.prompt)
            + u64::from(self.prefix.declared_prefix_tokens())
            + u64::from(self.decode)
    }
}

/// Per-admission monotonic sequence used for stable policy tie-breaking.
#[derive(Default)]
pub(crate) struct EnqueueSequence {
    next: u64,
}

impl EnqueueSequence {
    pub(crate) fn freeze(
        &mut self,
        request: RequestId,
        prompt: u32,
        decode: u32,
        prefix: PrefixInput,
    ) -> AdmissionCandidate {
        let enqueue_sequence = self.next;
        self.next = self
            .next
            .checked_add(1)
            .expect("admission enqueue sequence overflow");
        AdmissionCandidate {
            request,
            enqueue_sequence,
            prompt,
            decode,
            prefix,
            deadline: None,
            matched_tokens: 0,
        }
    }
}

/// Owns the pending set and selects one stable head for the lifecycle to gate.
pub trait PendingOrderPolicy {
    type Context;

    fn push(&mut self, candidate: AdmissionCandidate, context: &mut Self::Context);
    fn peek(&self) -> Option<AdmissionCandidate>;
    fn pop(&mut self, context: &mut Self::Context) -> Option<AdmissionCandidate>;
    fn remove(&mut self, request: RequestId) -> Option<AdmissionCandidate>;
    fn contains(&self, request: RequestId) -> bool;
    fn len(&self) -> usize;
    fn queued_kv_tokens(&self) -> u64;

    #[inline]
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}
