"""Typed TraceLab configuration embedded in a YAML/JSON profiling config.

Trace frontends are a tagged union because session and independent-request
traces already have distinct runtime behavior. Request construction currently
has one concrete synthetic-text path, so its inputs stay direct workload fields
until a second implementation introduces real runtime dispatch.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import ClassVar


@dataclass
class SessionFrontendConfig:
    """A canonical `session-execution-v2` trace.

    There is no context-policy field: the prefix/append split is resolved when
    the trace is generated by `tracegen` and recorded in the manifest beside it,
    so a profiling config selects a materialized file rather than a rule for
    materializing one.
    """

    type: ClassVar[str] = "session"
    path: str


@dataclass
class IndependentFrontendConfig:
    type: ClassVar[str] = "independent"
    path: str


FrontendConfig = SessionFrontendConfig | IndependentFrontendConfig
_FRONTEND_CONFIGS = {
    SessionFrontendConfig.type: SessionFrontendConfig,
    IndependentFrontendConfig.type: IndependentFrontendConfig,
}


@dataclass
class OpenAIBackendConfig:
    type: ClassVar[str] = "openai"
    cli_value: ClassVar[str] = "openai"
    required_server_args: ClassVar[tuple[str, ...]] = ()


@dataclass
class VllmTokensBackendConfig:
    type: ClassVar[str] = "vllm_tokens"
    cli_value: ClassVar[str] = "vllm-tokens"
    required_server_args: ClassVar[tuple[str, ...]] = ("--tokens-only",)


BackendConfig = OpenAIBackendConfig | VllmTokensBackendConfig
_BACKEND_CONFIGS = {
    OpenAIBackendConfig.type: OpenAIBackendConfig,
    VllmTokensBackendConfig.type: VllmTokensBackendConfig,
}


def _load_tagged_config(value: dict, registry: dict, field_name: str):
    if not isinstance(value, dict):
        raise ValueError(f"{field_name} must be a mapping")
    raw = dict(value)
    tag = raw.pop("type", None)
    config_type = registry.get(tag)
    if config_type is None:
        raise ValueError(
            f"unsupported {field_name}.type {tag!r}; available: {sorted(registry)}"
        )
    try:
        return config_type(**raw)
    except TypeError as exc:
        raise ValueError(f"invalid {field_name} config: {exc}") from exc


@dataclass
class LoadGeneratorConfig:
    """TraceLab frontend, synthetic-text inputs, and replay policy."""

    frontend: FrontendConfig
    text_file: str
    tokenizer: str
    backend: BackendConfig = field(default_factory=OpenAIBackendConfig)
    max_items: int | None = None
    rate: float | None = None
    # Where release times come from. Orthogonal to `max_concurrency`, which caps
    # how many units run at once rather than when they may start.
    arrival_mode: str = "trace-timed"
    token_pool_limit: int | None = None
    stream_idle_timeout_secs: int = 600
    max_concurrency: int | None = None
    max_model_len: int | None = None
    skip_when_reaching_limit: bool = False
    # Deprecated compatibility field. New configs should use
    # `skip_when_reaching_limit`.
    fail_on_context_overflow: bool = False
    extra_args: list[str] = field(default_factory=list)

    ARRIVAL_MODES: ClassVar[tuple[str, ...]] = ("trace-timed", "saturated")

    def __post_init__(self) -> None:
        if self.context_limit_skip_enabled and self.max_model_len is None:
            raise ValueError(
                "skip_when_reaching_limit requires max_model_len"
            )
        if self.arrival_mode not in self.ARRIVAL_MODES:
            raise ValueError(
                f"unknown arrival_mode {self.arrival_mode!r} "
                f"(expected one of {list(self.ARRIVAL_MODES)})"
            )
        if self.arrival_mode == "saturated" and self.rate is not None:
            raise ValueError(
                "rate rescales the trace's arrival timeline, which "
                "arrival_mode 'saturated' discards; set one or the other"
            )

    @property
    def context_limit_skip_enabled(self) -> bool:
        return self.skip_when_reaching_limit or self.fail_on_context_overflow

    @classmethod
    def from_mapping(cls, value: dict) -> LoadGeneratorConfig:
        if not isinstance(value, dict):
            raise ValueError("profiling workload must be a mapping")
        raw = dict(value)
        try:
            frontend_raw = raw.pop("frontend")
        except KeyError as exc:
            raise ValueError(f"profiling workload missing {exc.args[0]!r}") from exc
        frontend = _load_tagged_config(frontend_raw, _FRONTEND_CONFIGS, "frontend")
        backend_raw = raw.pop("backend", None)
        backend = (
            OpenAIBackendConfig()
            if backend_raw is None
            else _load_tagged_config(backend_raw, _BACKEND_CONFIGS, "backend")
        )
        try:
            return cls(frontend=frontend, backend=backend, **raw)
        except TypeError as exc:
            raise ValueError(f"invalid profiling workload: {exc}") from exc
